name: nimPDF CI
on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        version:
          - stable

    steps:
    - uses: actions/checkout@v2

    - name: Cache choosenim
      id: cache-choosenim
      uses: actions/cache@v2
      with:
        path: ~/.choosenim
        key: ${{ runner.os }}-choosenim-1.4.6

    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v2
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble-1.4.6

    - name: Install Nim
      if: steps.cache-choosenim.outputs.cache-hit != 'true' || steps.cache-nimble.outputs.cache-hit != 'true'
      run: |
        export CHOOSENIM_CHOOSE_VERSION="1.4.6"
        curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
        sh init.sh -y

    - name: Print Nim version
      run: nim -v

    - name: Print Nimble version
      run: nimble -v

    - name: Nimble Refresh
      run: nimble -y refresh

    - name: Nimble Install dependencies
      run: nimble -y install --depsOnly

    - name: Nimble test
      run: nimble test